name: fixera-backend
services:
  postgres:
    image: postgres:15-alpine
    container_name: fixera_postgres
    restart: always
    environment:
      POSTGRES_USER: fixera_user
      POSTGRES_PASSWORD: fixera_password
      POSTGRES_DB: fixera_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: