name: tikir-backend
services:
  postgres:
    image: postgres:16-alpine
    container_name: tikir_postgres
    restart: always
    environment:
      POSTGRES_USER: tikir_user
      POSTGRES_PASSWORD: tikir_password
      POSTGRES_DB: tikir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: